version: "2"
services:
  valheim:
    image: jazo10/docker-valheim:latest
    environment:
      - SERVER_NAME=Docker Valheim
      - SERVER_PASSWORD=server-password
      - SERVER_WORLD=Dedicated
      - SERVER_PORT=2456
    ports:
      - '2456:2456/udp'
      - '2457:2457/udp'
      - '2458:2458/udp'
      - '2456:2456/tcp'
      - '2457:2457/tcp'
      - '2458:2458/tcp'
    volumes:
      - :/home/valheim/app:/home/valheim
      - :/home/valheim/config:~/.config/unity3d/IronGate/Valheim
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
